apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-containerizing-spring
spec:
  title: Containerizing a Spring Boot application
  description: A workshop describing how to run a Spring Boot application in docker.
  publish:
    image: $(image_repository)/lab-containerizing-spring-files:$(workshop_version)
  workshop:
    image: jdk17-environment:*
    files:
    - image:
        url: $(image_repository)/lab-containerizing-spring-files:$(workshop_version)
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
      newRootPath: workshops/lab-containerizing-spring
  session:
    resources:
      memory: 1Gi
    namespaces:
      security:
        token:
          enabled: false
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      docker:
        enabled: true
    ingresses:
    - name: demo
      port: 8080
