apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-creating-a-spring-app
spec:
  title: Creating a Spring Boot application
  description: A workshop introducing the start.spring.io web site.
  publish:
    image: $(image_repository)/labs-creating-a-spring-app-files:$(workshop_version)
  workshop:
    image: jdk17-environment:*
    files:
    - image:
        url: $(image_repository)/labs-creating-a-spring-app-files:$(workshop_version)
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
    - path: .m2
      image:
        url: ghcr.io/educates/lab-spring-boot-on-k8s-maven:latest
  session:
    resources:
      memory: 1Gi
    namespaces:
      security:
        token:
          enabled: false
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
    dashboards:
    - name: Initializr
      url: $(ingress_protocol)://initializr-$(session_namespace).$(ingress_domain)
    ingresses:
    - name: initializr
      protocol: http
      host: initializr.$(workshop_namespace).svc.cluster.local
      port: 8080
    - name: demo
      port: 8080
  environment:
    objects:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: initializr
        labels:
          app: initializr
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: initializr
        template:
          metadata:
            labels:
              app: initializr
          spec:
            containers:
            - name: dashboard
              image: ghcr.io/vmware-tanzu-labs/educates-spring-initializr:2.0
              imagePullPolicy: Always
              ports:
              - name: 8080-tcp
                containerPort: 8080
                protocol: TCP
    - apiVersion: v1
      kind: Service
      metadata:
        name: initializr
        labels:
          app: initializr
      spec:
        type: ClusterIP
        selector:
          app: initializr
        ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
