name: Publish Workshops

on:
  push:
    tags:
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-alpha.[0-9]+"
      - "[0-9]+.[0-9]+-beta.[0-9]+"
      - "[0-9]+.[0-9]+-rc.[0-9]+"
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  publish-workshops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        uses: educates/educates-github-actions/publish-multiple-workshops@v7
        with:
          token: ${{secrets.GITHUB_TOKEN}}
